import Image from "next/image";
import { Button } from "@/components/button";
import { SectionHeading } from "@/components/section-heading";
import { getSiteSettings } from "@/lib/api";

const skills = ["Product design","UX systems","Next.js","React","TypeScript","Responsive UI","Accessibility","Design systems","Content architecture","API-ready frontend","Performance","Prototyping"];

export default async function AboutPage() {
  const siteConfig = await getSiteSettings();
  return <div className="page">
    <section className="page-hero"><div className="container narrow"><p className="eyebrow">About {siteConfig.name}</p><h1>A professional home for the person behind the work.</h1><p className="hero-lede">The platform is designed to grow from portfolio to business, publishing, products, and eventually a full content-driven system.</p></div></section>
    <section className="section"><div className="container about-grid"><div><Image className="portrait-placeholder" src={siteConfig.avatar.src} width={520} height={520} alt={siteConfig.avatar.alt} /></div><div><p className="eyebrow">The story</p><h2>Curious by default. Precise when it matters.</h2><p className="body-large">I like building at the boundary between an idea and something people can actually use. That means asking better questions, simplifying the interface, and treating implementation as part of the design.</p><p className="body-large">Coralz keeps those pieces together: projects, services, experiments, writing, and products in one coherent digital home.</p><Button href="/contact">Work together</Button></div></div></section>
    <section className="section section--tint"><div className="container"><SectionHeading eyebrow="The journey" title="A practice that keeps evolving" /><div className="about-timeline"><article><span>01 · NOW</span><h3>Product-minded frontend</h3><p>Building thoughtful interfaces with scalable boundaries and a strong visual point of view.</p></article><article><span>02 · NEXT</span><h3>Products & publishing</h3><p>Turning experiments, resources, and ideas into useful public-facing things.</p></article><article><span>03 · LATER</span><h3>Connected platform</h3><p>Adding the independent backend, CMS, payments, analytics, and integrations when the foundation is ready.</p></article></div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="How I work" title="A few principles" /><div className="principles"><article><span>01</span><h3>Make the hierarchy obvious</h3><p>Good design makes the important thing easier to see, not merely more beautiful.</p></article><article><span>02</span><h3>Build for the next phase</h3><p>Frontend boundaries should make future APIs, CMS content, and integrations easier to add.</p></article><article><span>03</span><h3>Leave room for personality</h3><p>Polish is useful when it helps a product feel memorable without becoming noise.</p></article></div></div></section>
    <section className="section section--tint"><div className="container"><SectionHeading eyebrow="Values" title="What stays constant" /><div className="about-values"><article><h3>Clarity over clutter</h3><p>Every element earns its place.</p></article><article><h3>Useful over ornamental</h3><p>Visual craft should make the experience better.</p></article><article><h3>Extensible over disposable</h3><p>Today’s frontend should make tomorrow’s system easier.</p></article><article><h3>Human over generic</h3><p>A professional platform can still have a recognizable voice.</p></article></div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Toolkit" title="Skills & technologies" /><div className="tag-cloud">{skills.map(x => <span key={x}>{x}</span>)}</div></div></section>
  </div>;
}
